### ISSUE TITLE
Which variable to use for fitting?

### ISSUE THREAD

**Issue by ernewton** [allisony/lyapy#7]
Currently "flux_to_fit" is used for fitting rather than "flux_masked". Which should it be?

**Comment by allisony** [comment]
I want to add masking as optional. For my G140M and E140M Lyman alpha data, I masked the line centers always. But for my new G140L data, I can't mask the center. And actually, masking the line centers for any grating may not be necessary. I think I was assuming in 2016 that the residual airglow was larger than it actually it is. So leave it up to the user.
